var hierarchy =
[
    [ "Calculator", "class_calculator.html", null ],
    [ "Database", "class_database.html", null ],
    [ "LexerUTComputer", "class_lexer_u_t_computer.html", null ],
    [ "Literal", "class_literal.html", [
      [ "ComplexLiteral", "class_complex_literal.html", null ],
      [ "NumericLiteral", "class_numeric_literal.html", null ],
      [ "StringLiteral", "class_string_literal.html", [
        [ "AtomLiteral", "class_atom_literal.html", null ],
        [ "ExpressionLiteral", "class_expression_literal.html", null ],
        [ "ProgramLiteral", "class_program_literal.html", null ]
      ] ]
    ] ],
    [ "LiteralFactory", "class_literal_factory.html", null ],
    [ "Operator", "class_operator.html", [
      [ "CalculationOperator", "class_calculation_operator.html", [
        [ "OperatorAnd", "class_operator_and.html", null ],
        [ "OperatorDenominator", "class_operator_denominator.html", null ],
        [ "OperatorDifferent", "class_operator_different.html", null ],
        [ "OperatorDivision", "class_operator_division.html", null ],
        [ "OperatorDollar", "class_operator_dollar.html", null ],
        [ "OperatorEqual", "class_operator_equal.html", null ],
        [ "OperatorIM", "class_operator_i_m.html", null ],
        [ "OperatorInferior", "class_operator_inferior.html", null ],
        [ "OperatorInferiorEqual", "class_operator_inferior_equal.html", null ],
        [ "OperatorIntegerDivision", "class_operator_integer_division.html", null ],
        [ "OperatorMinus", "class_operator_minus.html", null ],
        [ "OperatorModulo", "class_operator_modulo.html", null ],
        [ "OperatorMultiplication", "class_operator_multiplication.html", null ],
        [ "OperatorNeg", "class_operator_neg.html", null ],
        [ "OperatorNot", "class_operator_not.html", null ],
        [ "OperatorNumerator", "class_operator_numerator.html", null ],
        [ "OperatorOr", "class_operator_or.html", null ],
        [ "OperatorPlus", "class_operator_plus.html", null ],
        [ "OperatorRE", "class_operator_r_e.html", null ],
        [ "OperatorSuperior", "class_operator_superior.html", null ],
        [ "OperatorSuperiorEqual", "class_operator_superior_equal.html", null ]
      ] ],
      [ "StackOperator", "class_stack_operator.html", [
        [ "OperatorCLEAR", "class_operator_c_l_e_a_r.html", null ],
        [ "OperatorDROP", "class_operator_d_r_o_p.html", null ],
        [ "OperatorDUP", "class_operator_d_u_p.html", null ],
        [ "OperatorLASTARGS", "class_operator_l_a_s_t_a_r_g_s.html", null ],
        [ "OperatorLASTOP", "class_operator_l_a_s_t_o_p.html", null ],
        [ "OperatorREDO", "class_operator_r_e_d_o.html", null ],
        [ "OperatorSWAP", "class_operator_s_w_a_p.html", null ],
        [ "OperatorUNDO", "class_operator_u_n_d_o.html", null ]
      ] ]
    ] ],
    [ "OperatorManager", "class_operator_manager.html", null ],
    [ "QMainWindow", null, [
      [ "MainWindow", "class_main_window.html", null ]
    ] ],
    [ "StackUTComputer", "class_stack_u_t_computer.html", null ],
    [ "StackUTComputerMemento", "class_stack_u_t_computer_memento.html", null ],
    [ "Test", null, [
      [ "Test_Atom_Literal", "class_test___atom___literal.html", null ],
      [ "Test_Calculator", "class_test___calculator.html", null ],
      [ "Test_Complex_Literal", "class_test___complex___literal.html", null ],
      [ "Test_Expression_Literal", "class_test___expression___literal.html", null ],
      [ "Test_Lexer_Class", "class_test___lexer___class.html", null ],
      [ "Test_Literal_Factory", "class_test___literal___factory.html", null ],
      [ "Test_Numeric_Literal", "class_test___numeric___literal.html", null ],
      [ "Test_Operator_And", "class_test___operator___and.html", null ],
      [ "Test_Operator_Class", "class_test___operator___class.html", null ],
      [ "Test_Operator_CLEAR", "class_test___operator___c_l_e_a_r.html", null ],
      [ "Test_Operator_Denominator", "class_test___operator___denominator.html", null ],
      [ "Test_Operator_Different", "class_test___operator___different.html", null ],
      [ "Test_Operator_Division", "class_test___operator___division.html", null ],
      [ "Test_Operator_Dollar", "class_test___operator___dollar.html", null ],
      [ "Test_Operator_DROP", "class_test___operator___d_r_o_p.html", null ],
      [ "Test_Operator_DUP", "class_test___operator___d_u_p.html", null ],
      [ "Test_Operator_Equal", "class_test___operator___equal.html", null ],
      [ "Test_Operator_IM", "class_test___operator___i_m.html", null ],
      [ "Test_Operator_Inferior", "class_test___operator___inferior.html", null ],
      [ "Test_Operator_InferiorEqual", "class_test___operator___inferior_equal.html", null ],
      [ "Test_Operator_Int_Div", "class_test___operator___int___div.html", null ],
      [ "Test_Operator_LASTARGS", "class_test___operator___l_a_s_t_a_r_g_s.html", null ],
      [ "Test_Operator_LASTOP", "class_test___operator___l_a_s_t_o_p.html", null ],
      [ "Test_Operator_Manager", "class_test___operator___manager.html", null ],
      [ "Test_Operator_Minus", "class_test___operator___minus.html", null ],
      [ "Test_Operator_Mod", "class_test___operator___mod.html", null ],
      [ "Test_Operator_Multiplication", "class_test___operator___multiplication.html", null ],
      [ "Test_Operator_Neg", "class_test___operator___neg.html", null ],
      [ "Test_Operator_Not", "class_test___operator___not.html", null ],
      [ "Test_Operator_Numerator", "class_test___operator___numerator.html", null ],
      [ "Test_Operator_Or", "class_test___operator___or.html", null ],
      [ "Test_Operator_Plus", "class_test___operator___plus.html", null ],
      [ "Test_Operator_RE", "class_test___operator___r_e.html", null ],
      [ "Test_Operator_Superior", "class_test___operator___superior.html", null ],
      [ "Test_Operator_SuperiorEqual", "class_test___operator___superior_equal.html", null ],
      [ "Test_Operator_SWAP", "class_test___operator___s_w_a_p.html", null ],
      [ "Test_Operator_UNDO_REDO", "class_test___operator___u_n_d_o___r_e_d_o.html", null ],
      [ "Test_Program_Literal", "class_test___program___literal.html", null ],
      [ "Test_StackUTComputer_Class", "class_test___stack_u_t_computer___class.html", null ]
    ] ],
    [ "UTComputerException", "class_u_t_computer_exception.html", null ]
];